Library/Models/Publisher.cs
namespace Library.Models
{
    public class Publisher
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public int StablishedAt { get; set; }

        public virtual ICollection<Book> Books { get; set; }

    }
}

Library/Controllers/PublisherController.cs
using Library.Models;
using Library.Repositories;
using Library.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{
    [Authorize]
    public class PublisherController : Controller
    {
        private readonly IPublisherRepository publisher;

        public PublisherController(IPublisherRepository _publisher)
        {
            publisher = _publisher;
        }
        public IActionResult Index()
        {
            return View("AllPublishers", publisher.GetPublishers());
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]

        public IActionResult Add(PublisherVM model)
        {
            Publisher publish = new Publisher();
            if (ModelState.IsValid)
            {
                publish.Name = model.Name;
                publish.Phone = model.Phone;
                publish.StablishedAt = model.StablishedAt;
                publisher.AddPublisher(publish);
                return RedirectToAction("Index");
            }
            return View();

        }
        [HttpGet]
        public IActionResult Edit(int id)
        {


            return View( publisher.findById(id));
        }
        [HttpPost]
        public IActionResult Edit(int id, PublisherVM publisherVM)
        {
            Publisher publish = new Publisher();
            if (ModelState.IsValid)
            {
                publish.Name = publisherVM.Name;
                publish.Phone = publisherVM.Phone;
                publish.StablishedAt = publisherVM.StablishedAt;
                publisher.Edit(id, publish);
                return RedirectToAction("Index");
            }
            return View(publisher.findById(id));
        }
        public IActionResult Delete(int id)
        {
            publisher.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Library/Views/Publisher/Add.cshtml
@using Library.ViewModel
@model PublisherVM
@{
    Layout = "_AdminLayout";
}

<div class="row">
     <div class="col-md-2"></div>
    <div class="col-md-8">
        <h2 class="text-center shadow  mb-3 p-3">Add New Publisher</h2>
<hr />
         <form asp-action="Add">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StablishedAt" class="control-label"></label>
                <input asp-for="StablishedAt" class="form-control" />
                <span asp-validation-for="StablishedAt" class="text-danger"></span>
            </div>

            <div class="row mt-5 mb-5">
                <div class="col-12 col-md-6">
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn form-control btn btn-outline-success" />
                    </div>
                </div>
                <div class="col-12 col-md-6">
                     <a asp-action="Index" class="form-control btn btn-outline-dark ">Back To Publishers</a>
                </div>
            </div>
            
        </form>
    </div>
    <div class="col-md-2"></div>
</div>









@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Library/Views/Publisher/AllPublishers.cshtml
@model List<Publisher>
@{
    Layout = "_AdminLayout";
}

@*<a href="/Publisher/Add" class="btn btn-success">Add New</a>*@
<div class="row">
    <h2 class="text-center shadow  mb-5 p-3">Publishers</h2>
    @foreach (Publisher item in Model)
    {
        <div class="col-12 col-md-6 shadow mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">@item.Name</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Published At : @item.StablishedAt</h6>
                    <p class="card-text">Contact No : @item.Phone</p>
                    <a href="/Publisher/Edit/@item.Id" title="Edit" class="card-link fs-3 text-success"><i class="fa-solid fa-pen-to-square"></i></a>
                    <a href="#" title="Remove" class="card-link fs-3 text-danger" data-bs-toggle="modal" data-bs-target="#myModal-@item.Id"><i class="fa-solid fa-trash-can"></i></a>
                </div>
            </div>

        </div>

        <!-- The Modal -->
        <div class="modal" id="myModal-@item.Id">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">

                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title">Delete Publisher</h4>
                        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">
                        Are You Sure To Delete Publisher <strong>@item.Name</strong>
                    </div>

                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <form asp-action="Delete" asp-controller="Publisher" asp-route-id="@item.Id" method="post">
                            <input type="submit" value="Confirm" class="btn btn-outline-danger" />
                        </form>
                        <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">Close</button>
                    </div>

                </div>
            </div>
        </div>
    }
</div>

Library/Views/Publisher/Edit.cshtml
@model Publisher
@{
    Layout = "_AdminLayout";
}

<div class="row">
     <div class="col-md-2"></div>
    <div class="col-md-8">
        <h2 class="text-center shadow  mb-3 p-3">Edit Publisher</h2>
<hr />
        <form asp-action="Edit">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StablishedAt" class="control-label"></label>
                <input asp-for="StablishedAt" class="form-control" />
                <span asp-validation-for="StablishedAt" class="text-danger"></span>
            </div>

            <div class="row mt-5 mb-5">
                <div class="col-12 col-md-6">
                    <div class="form-group">
                        <input type="submit" value="Save" class="form-control  btn btn-primary" />
                    </div>
                </div>
                <div class="col-12 col-md-6">
                     <a asp-action="Index" class="form-control btn btn-outline-dark ">Back To Publishers</a>
                </div>
            </div>
            
        </form>
    </div>
    <div class="col-md-2"></div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}